// ExplosionPlayer.cs
// Plays a per-frame mesh swap animation of the 3D blowup explosion.
// The frames are generated by Tools/Vox_Generator/death_explosion_to_obj.py and played
// from code by CreatureDying; the manual setup below still works for a scene object.
//
// CreatureDying sets frameDurations (the first frames held longer) and a burst scale-up.
//
// Setup:
//   1. Import all explosion_00 .. explosion_04 .obj + .mtl files into Unity (drag into Project window).
//      Unity imports them as Models. Their bounding boxes are identical (36 x 36 x 36 centred at origin),
//      so the pivot does NOT shift between frames.
//   2. Create an empty GameObject in the scene. Add a MeshFilter and MeshRenderer component.
//   3. Add this script to the GameObject.
//   4. Drag the 8 imported meshes (in order 04 -> 11) into the `frames` array in the Inspector.
//      You can find each mesh inside its imported Model asset (expand the model to see the Mesh child).
//   5. Optional: assign your own materials to the MeshRenderer.materials slot, or rely on the imported
//      ones generated from the .mtl files.
//   6. Set framesPerSecond to taste (10-15 fps usually feels right for a quick explosion).
//   7. Press Play. The script cycles through the meshes once and disables the renderer at the end
//      (or destroys the object if `destroyOnEnd` is true).

using UnityEngine;

[RequireComponent(typeof(MeshFilter))]
[RequireComponent(typeof(MeshRenderer))]
public class ExplosionPlayer : MonoBehaviour
{
    [Tooltip("Meshes for explosion frames in order (explosion_00 .. explosion_07).")]
    public Mesh[] frames;

    [Tooltip("Optional materials per frame (one per submesh); frames differ in colour count, so each frame carries its own set.")]
    public Material[][] frameMaterials;

    [Tooltip("Optional light whose intensity follows lightIntensities, one value per frame.")]
    public Light frameLight;
    public float[] lightIntensities;

    [Tooltip("Playback speed in frames per second.")]
    public float framesPerSecond = 12f;

    [Tooltip("Optional seconds each frame is held, one per frame; overrides framesPerSecond.")]
    public float[] frameDurations;

    [Tooltip("Burst from the centre: the whole explosion grows from burstStartScale to full size over burstSeconds (ease-out). 0 = off.")]
    public float burstSeconds = 0f;
    public float burstStartScale = 1f;

    [Tooltip("Restart from frame 0 every time the object is enabled.")]
    public bool playOnEnable = true;

    [Tooltip("If true, destroy the GameObject when the animation finishes.")]
    public bool destroyOnEnd = true;

    [Tooltip("If true, the renderer is left enabled after the last frame instead of being hidden.")]
    public bool keepLastFrameVisible = false;

    private MeshFilter   _filter;
    private MeshRenderer _renderer;
    private float        _time;
    private bool         _playing;
    private Vector3      _fullScale;

    private void Awake()
    {
        _filter   = GetComponent<MeshFilter>();
        _renderer = GetComponent<MeshRenderer>();
        _fullScale = transform.localScale;
    }

    private void OnEnable()
    {
        if (playOnEnable) Play();
    }

    public void Play()
    {
        _time    = 0f;
        _playing = true;
        ApplyBurst();
        if (frames != null && frames.Length > 0)
        {
            ShowFrame(0);
            _renderer.enabled  = true;
        }
    }

    private void Update()
    {
        if (!_playing || frames == null || frames.Length == 0) return;

        _time += Time.deltaTime;
        ApplyBurst();
        int idx = FrameAt(_time);

        if (idx >= frames.Length)
        {
            _playing = false;
            if (!keepLastFrameVisible) _renderer.enabled = false;
            if (destroyOnEnd) Destroy(gameObject);
            return;
        }

        if (_filter.sharedMesh != frames[idx])
            ShowFrame(idx);
    }

    /// <summary>The frame showing at time t; frames.Length once the last one is over.</summary>
    private int FrameAt(float t)
    {
        if (frameDurations == null || frameDurations.Length == 0)
            return Mathf.FloorToInt(t * framesPerSecond);

        for (int i = 0; i < frames.Length; i++)
        {
            float d = i < frameDurations.Length ? frameDurations[i] : 1f / framesPerSecond;
            if (t < d) return i;
            t -= d;
        }
        return frames.Length;
    }

    private void ApplyBurst()
    {
        if (burstSeconds <= 0f) return;
        float k = Mathf.Clamp01(_time / burstSeconds);
        k = 1f - (1f - k) * (1f - k) * (1f - k);   // ease-out: bursts fast, settles
        transform.localScale = _fullScale * Mathf.Lerp(burstStartScale, 1f, k);
    }

    private void ShowFrame(int idx)
    {
        _filter.sharedMesh = frames[idx];
        if (frameMaterials != null && idx < frameMaterials.Length && frameMaterials[idx] != null)
            _renderer.sharedMaterials = frameMaterials[idx];
        if (frameLight != null && lightIntensities != null && idx < lightIntensities.Length)
            frameLight.intensity = lightIntensities[idx];
    }
}
